name: pulsar-io-sqs integration tests

on:
  pull_request:
    branches:
      - master
      - branch-*
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: build
        run: mvn clean package -DskipTests

      - name: test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_on: error
          command: |
            ./.ci/integrations/test.sh
