name: pulsar-io-sqs sink tests

on:
  pull_request:
    branches:
      - master
      - branch-*
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: sqs
          DEFAULT_REGION: us-east-1
        ports:
          - 4566:4566

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: tests
        run: mvn -Dtest=SQSSinkTest test -DfailIfNoTests=false
